"""Python client utilities for Teamworks AMS/Smartabase."""

from .client import OperationExecution, SmartabaseClient
from .config import SmartabaseCredentials, load_credentials, normalize_url
from .dates import AMS_DATE_FORMAT, AMS_DATE_FORMAT_LABEL, format_ams_date, parse_ams_date
from .diagnostics import (
    AMSConnectorError,
    AMSDateFormatError,
    AMSEndpointFallbackWarning,
    AMSEventIdUnavailableError,
    AMSInputValidationError,
    AMSResponseShapeError,
    EndpointProvenance,
    EXACT_EVENT_ID_KEYS,
    MutationAssessment,
    MutationState,
    SUCCESS_COUNT_KEYS,
    SUCCESS_STATUSES,
    assess_operation_execution,
    discover_endpoint_provenance,
    response_confirms_success,
    smartabase_acceptance_state,
)
from .endpoints import DEFAULT_ENDPOINTS, EndpointMap
from .filters import (
    DATA_CONDITION_CODES,
    DataFilter,
    build_event_export_request,
    build_group_request,
    build_profile_export_request,
    build_sync_request,
    build_user_request,
    sb_date_range,
)
from .flatten import (
    find_event_records,
    find_profile_records,
    flatten_event_response,
    flatten_profile_response,
)
from .modes import (
    RUNNER_IDENTITY_ENV_VAR,
    AutoQualification,
    DestinationCollisionError,
    MissingQualificationError,
    ModeError,
    ModeNotAllowedForOperationError,
    NonInteractiveEnvironmentError,
    QualificationMismatchError,
    SafetyMode,
    UnknownSafetyModeError,
    check_auto_eligibility,
    check_destination_non_collision,
    compute_confirmation_phrase,
    is_real_tty,
    load_qualification,
    require_interactive_confirmation,
    require_operation_allowed,
    resolve_mode,
    write_qualification_interactively,
)
from .workflow import (
    DEFAULT_EXAMPLE_CONFIG,
    DEFAULT_EXAMPLE_CSV,
    EventCountResult,
    EventWriteTarget,
    ExampleEventWorkflowInput,
    build_event_write_targets,
    count_event_entries,
    require_exact_event_ids,
    run_event_delete_workflow,
    load_example_event_workflow_input,
    plan_event_deletions,
    run_example_event_delete,
    run_event_replay_workflow,
    run_event_replace_workflow,
    run_example_event_replay,
)
from .payloads import (
    PayloadPackage,
    build_delete_payloads,
    build_event_import_payloads,
    build_profile_upsert_payloads,
    coerce_records_input,
    select_metadata,
    suggest_nested_table_candidates,
)
from .roster import RosterEntry, fetch_roster, flatten_roster_response, resolve_user_ids
from .smoke_test import run_smoke_test

__all__ = [
    "AthleteInitializationResult",
    "AMSConnectorError",
    "AMSDateFormatError",
    "AMS_DATE_FORMAT",
    "AMS_DATE_FORMAT_LABEL",
    "AMSEndpointFallbackWarning",
    "AMSEventIdUnavailableError",
    "AMSInputValidationError",
    "AMSResponseShapeError",
    "AutoQualification",
    "DestinationCollisionError",
    "MissingQualificationError",
    "ModeError",
    "ModeNotAllowedForOperationError",
    "NonInteractiveEnvironmentError",
    "QualificationMismatchError",
    "RUNNER_IDENTITY_ENV_VAR",
    "SafetyMode",
    "UnknownSafetyModeError",
    "check_auto_eligibility",
    "check_destination_non_collision",
    "compute_confirmation_phrase",
    "is_real_tty",
    "load_qualification",
    "require_interactive_confirmation",
    "require_operation_allowed",
    "resolve_mode",
    "write_qualification_interactively",
    "DATA_CONDITION_CODES",
    "DEFAULT_ENDPOINTS",
    "DEFAULT_EXAMPLE_CONFIG",
    "DEFAULT_EXAMPLE_CSV",
    "DataFilter",
    "EndpointMap",
    "EndpointProvenance",
    "EXACT_EVENT_ID_KEYS",
    "EventCountResult",
    "EventWriteTarget",
    "ExampleEventWorkflowInput",
    "OperationExecution",
    "MutationAssessment",
    "MutationState",
    "SUCCESS_COUNT_KEYS",
    "SUCCESS_STATUSES",
    "PayloadPackage",
    "RosterEntry",
    "SmartabaseClient",
    "SmartabaseCredentials",
    "build_delete_payloads",
    "assess_operation_execution",
    "build_event_export_request",
    "build_event_import_payloads",
    "build_event_write_targets",
    "build_group_request",
    "build_profile_export_request",
    "build_profile_upsert_payloads",
    "coerce_records_input",
    "build_sync_request",
    "build_user_request",
    "count_event_entries",
    "discover_endpoint_provenance",
    "find_event_records",
    "find_profile_records",
    "flatten_event_response",
    "flatten_profile_response",
    "flatten_roster_response",
    "format_ams_date",
    "initialize_sandbox_athletes",
    "load_example_event_workflow_input",
    "load_credentials",
    "normalize_url",
    "plan_event_deletions",
    "parse_ams_date",
    "fetch_roster",
    "resolve_user_ids",
    "require_exact_event_ids",
    "response_confirms_success",
    "run_event_delete_workflow",
    "run_example_event_delete",
    "run_event_replay_workflow",
    "run_event_replace_workflow",
    "run_example_event_replay",
    "run_smoke_test",
    "sb_date_range",
    "select_metadata",
    "suggest_nested_table_candidates",
    "smartabase_acceptance_state",
]


def __getattr__(name: str) -> object:
    """Lazily expose initializer APIs without preloading its CLI module."""

    if name in {"AthleteInitializationResult", "initialize_sandbox_athletes"}:
        from .initializer import (
            AthleteInitializationResult,
            initialize_sandbox_athletes,
        )

        return {
            "AthleteInitializationResult": AthleteInitializationResult,
            "initialize_sandbox_athletes": initialize_sandbox_athletes,
        }[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
